<?php

namespace QSOBundle\Repository;

/**
 * CallsignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallsignRepository extends \Doctrine\ORM\EntityRepository
{
}
