<?php

namespace QSOBundle\Repository;

/**
 * FrequencyUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrequencyUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
