<?php

namespace QSOBundle\Repository;

/**
 * RadioModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadioModeRepository extends \Doctrine\ORM\EntityRepository
{
}
